### ISSUE TITLE
Parse existing configurations

### ISSUE THREAD

**Issue by piotrkochan** [jipipayo/SphinxConfigBuilder#1]
Script's cool, but there should be an option to parse existing sphinx configurations and extend them. Then you could only change few fields in every index or source

**Comment by jipipayo** [comment]
Thanks @pikey666 for the feedback... The idea of this module is to get rid of the classical sphinx plaintext file, and be able to output a same plain text but from dynamic data. For instance: get your db connection from you application configuration, so will be easier to deploy on more than one server. I think i am not going to make this plain text parser.  is out of the scope of this project.
